baseURL = "https://eigen.sh/"
languageCode = "en-us"
title = "eigen.sh"
theme = "coder-portfolio"

DefaultContentLanguage = "en"

paginate = 20

pygmentsstyle = "b2"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true
pygmentsUseClasses = true


[params]
    author = "Sam Eigen"
    description = "code - hacking - blockchain"
    keywords = "blog,developer,personal,cardano,staking,pool,cybersecurity,netsec,cybersec,python"
    info = "SOFTWARE ENGINEER, BLOCKCHAIN ENTHUSIAST, WHITE-HAT HACKER"
    avatarurl = "images/avatar.jpg"
    fixedbarContent = "Current projects: "
    fixedbarContentAfter = "Please don't hesitate to reach out if you have any questions!"

    hideCredits = true
    hideCopyright = true

    snsShare = true
    enableTwitterShare = true
    enableLinkedInShare = true

    thumbnail = "images/thumb.png"

    # Custom CSS
    custom_css = []

    # Alignment of Mobile Menu items
    itemscentered = true

    # RTL support
    rtl = false

    langseparator = "|"

[[params.social]]
    name = "Github"
    icon = "fab fa-github"
    weight = 1
    url = "https://github.com/k0ley/"
[[params.social]]
    name = "Twitter"
    icon = "fab fa-twitter"
    weight = 2
    url = "https://twitter.com/legitneth/"
[[params.social]]
    name = "LinkedIn"
    icon = "fab fa-linkedin"
    weight = 3
    url = "https://www.linkedin.com/in/samuel-eigen/"


[[menu.main]]
    name = "Blog"
    weight = 1
    url = "posts"

[[menu.main]]
    name = "Projects"
    weight = 2
    url = "projects"

[[menu.main]]
    name = "Blockchain"
    weight = 3
    url = "blockchain"

[[menu.main]]
    name = "About"
    weight = 4
    url = "about"
